### ISSUE TITLE
x86 Build Crashes Immediately 

### ISSUE THREAD

**Issue by JarrydHuntley** [PlayEveryWare/eos_plugin_for_unity#110]
**Describe the bug**
Build an x86 build with the Epic Online Services Plugin for Unity is included causes the build to immediately crash. I was able to reproduce this behavior in a blank project that only contains the sample scenes. If you build the project and launch, it'll crash immediately on boot when build targeting x86. If the exact same project is build targeting x86_64 everything works as intended.

**To Reproduce**
1. Create an empty project
2. Import the Epic Online Services Plugin for Unity in the package manager.
3. Install the sample scenes.
4. Configure the Epic Online Services Plugin for Unity.
4. b.) If the known issue #105 has not been built into the plugin yet, follow the steps listed in the issues and remove the troublesome values from the json file.
5. Add all the sample scenes in the Scenes In Build list.
6. Be sure x86 is the target Architecture.
7. Build the project.
8. Launch the .exe and observe the crash

**Expected behavior**
The built project is expected to run without immediately crashing.

**Desktop:**
 - OS: Windows 10 Pro
 - Unity Version: Unity 2020.3.33f1
 - Plugin Version: 2.0.1

**Additional context**
I was unsure if the crash was due to DynamicLibraryLoaderHelper.dll and GfxPluginNativeRender-x86.dll not being marked as "Load on Startup" for x86, but after changing those the build still continued to crash.

Here is the resulting log from the crash:

```
Mono path[0] = 'C:/Temp/EOS_Test/Epic EOS Test_Data/Managed'
Mono config path = 'C:/Temp/EOS_Test/MonoBleedingEdge/etc'
Initialize engine version: 2020.3.33f1 (915a7af8b0d5)
[Subsystems] Discovering subsystems at path C:/Temp/EOS_Test/Epic EOS Test_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 (ID=0x1c20)
    Vendor:   (null)
    VRAM:     3072 MB
    Driver:   27.21.14.6109
Begin MonoManager ReloadAssembly
- Completed reload, in  0.920 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 2.341900 ms
Start of Early EOS LOG:
2022-08-09T20:16:40.068 NativePlugin (INFORM): about to look with exists
2022-08-09T20:16:40.068 NativePlugin (INFORM): Trying to load eos config via dll
2022-08-09T20:16:40.068 NativePlugin (INFORM): Loading path at C:\Temp\EOS_Test\Epic EOS Test_Data\Plugins\x86\EOSGenerated.dll
2022-08-09T20:16:40.068 NativePlugin (WARNING): No Generated DLL found (Might not be an error)
2022-08-09T20:16:40.068 NativePlugin (INFORM): json pathC:\Temp\EOS_Test\Epic EOS Test_Data\Plugins\x86\../..\StreamingAssets\EOS\EpicOnlineServicesConfig.json
2022-08-09T20:16:40.069 NativePlugin (INFORM): On UnityPluginLoad
2022-08-09T20:16:40.069 NativePlugin (INFORM): Loading path at C:\Temp\EOS_Test\Epic EOS Test_Data\Plugins\x86\EOSSDK-Win32-Shipping.dll
2022-08-09T20:16:40.108 NativePlugin (INFORM): start eos init
2022-08-09T20:16:40.108 NativePlugin (INFORM): call EOS_Initialize
2022-08-09T20:16:40.131 NativePlugin (INFORM): setting up rtc
2022-08-09T20:16:40.131 NativePlugin (WARNING): C:\Temp\EOS_Test\Epic EOS Test_Data\Plugins\x86\xaudio2_9redist.dll
2022-08-09T20:16:40.131 NativePlugin (INFORM): about to look with exists
2022-08-09T20:16:40.132 NativePlugin (INFORM): run EOS_Platform_Create
Crash!!!
SymInit: Symbol-SearchPath: '.;C:\Temp\EOS_Test;C:\Temp\EOS_Test;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 534, UserName: 'xxxxx'
OS-Version: 10.0.0
C:\Temp\EOS_Test\Epic EOS Test.exe:Epic EOS Test.exe (00E80000), size: 655360 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2020.3.33.23162
C:\WINDOWS\SYSTEM32\ntdll.dll:ntdll.dll (77400000), size: 1720320 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\WINDOWS\System32\KERNEL32.DLL:KERNEL32.DLL (75CE0000), size: 983040 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1826
C:\WINDOWS\System32\KERNELBASE.dll:KERNELBASE.dll (76A80000), size: 2199552 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1826
C:\WINDOWS\SYSTEM32\apphelp.dll:apphelp.dll (75230000), size: 651264 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1320
C:\Temp\EOS_Test\UnityPlayer.dll:UnityPlayer.dll (788D0000), size: 22728704 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2020.3.33.23162
C:\WINDOWS\System32\USER32.dll:USER32.dll (76790000), size: 1687552 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1826
C:\WINDOWS\System32\win32u.dll:win32u.dll (76270000), size: 98304 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1826
C:\WINDOWS\System32\GDI32.dll:GDI32.dll (76000000), size: 143360 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1620
C:\WINDOWS\System32\gdi32full.dll:gdi32full.dll (752D0000), size: 901120 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1826
C:\WINDOWS\System32\msvcp_win.dll:msvcp_win.dll (75F80000), size: 503808 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.789
C:\WINDOWS\System32\ucrtbase.dll:ucrtbase.dll (758D0000), size: 1179648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.789
C:\WINDOWS\System32\ole32.dll:ole32.dll (75BF0000), size: 929792 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1202
C:\WINDOWS\System32\RPCRT4.dll:RPCRT4.dll (769C0000), size: 778240 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\WINDOWS\System32\combase.dll:combase.dll (75480000), size: 2617344 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1741
C:\WINDOWS\SYSTEM32\VERSION.dll:VERSION.dll (740A0000), size: 32768 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\System32\SHLWAPI.dll:SHLWAPI.dll (766D0000), size: 282624 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1706
C:\WINDOWS\System32\msvcrt.dll:msvcrt.dll (753B0000), size: 782336 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 7.0.19041.546
C:\WINDOWS\System32\SETUPAPI.dll:SETUPAPI.dll (76290000), size: 4427776 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1741
C:\WINDOWS\System32\cfgmgr32.dll:cfgmgr32.dll (760B0000), size: 241664 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1620
C:\WINDOWS\System32\bcrypt.dll:bcrypt.dll (760F0000), size: 102400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1023
C:\WINDOWS\System32\ADVAPI32.dll:ADVAPI32.dll (75B70000), size: 503808 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1682
C:\WINDOWS\System32\sechost.dll:sechost.dll (75ED0000), size: 483328 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1586
C:\WINDOWS\System32\SHELL32.dll:SHELL32.dll (76DA0000), size: 5988352 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\WINDOWS\System32\OLEAUT32.dll:OLEAUT32.dll (76CA0000), size: 614400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.985
C:\WINDOWS\System32\IMM32.dll:IMM32.dll (75F50000), size: 151552 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\OPENGL32.dll:OPENGL32.dll (5B570000), size: 1064960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\WINDOWS\SYSTEM32\WINMM.dll:WINMM.dll (74140000), size: 163840 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\System32\CRYPT32.dll:CRYPT32.dll (76170000), size: 1024000 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1320
C:\WINDOWS\System32\WS2_32.dll:WS2_32.dll (75B00000), size: 405504 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\WINHTTP.dll:WINHTTP.dll (75040000), size: 823296 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1682
C:\WINDOWS\SYSTEM32\HID.DLL:HID.DLL (74170000), size: 40960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\GLU32.dll:GLU32.dll (5B0E0000), size: 258048 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\WINDOWS\SYSTEM32\dwmapi.dll:dwmapi.dll (736A0000), size: 155648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\WINDOWS\SYSTEM32\kernel.appcore.dll:kernel.appcore.dll (740F0000), size: 61440 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\System32\bcryptPrimitives.dll:bcryptPrimitives.dll (76110000), size: 389120 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1415
C:\WINDOWS\system32\uxtheme.dll:uxtheme.dll (736D0000), size: 475136 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1620
C:\WINDOWS\System32\shcore.dll:shcore.dll (76930000), size: 552960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1645
C:\WINDOWS\SYSTEM32\windows.storage.dll:windows.storage.dll (74370000), size: 6340608 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\WINDOWS\SYSTEM32\Wldp.dll:Wldp.dll (74100000), size: 159744 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\WINDOWS\SYSTEM32\profapi.dll:profapi.dll (73650000), size: 98304 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.844
C:\Temp\EOS_Test\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll:mono-2.0-bdwgc.dll (79E80000), size: 4456448 (result: 0), SymType: '-deferred-', PDB: ''
C:\WINDOWS\System32\PSAPI.DLL:PSAPI.DLL (75470000), size: 24576 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\iphlpapi.dll:iphlpapi.dll (75190000), size: 204800 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Temp\EOS_Test\Epic EOS Test_Data\Plugins\x86\DynamicLibraryLoaderHelper.dll:DynamicLibraryLoaderHelper.dll (508E0000), size: 114688 (result: 0), SymType: '-deferred-', PDB: ''
C:\Temp\EOS_Test\Epic EOS Test_Data\Plugins\x86\GfxPluginNativeRender-x86.dll:GfxPluginNativeRender-x86.dll (50870000), size: 397312 (result: 0), SymType: '-deferred-', PDB: ''
C:\Temp\EOS_Test\Epic EOS Test_Data\Plugins\x86\EOSSDK-Win32-Shipping.dll:EOSSDK-Win32-Shipping.dll (7A2C0000), size: 15196160 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 1.15.1.0
C:\WINDOWS\System32\WLDAP32.dll:WLDAP32.dll (76730000), size: 356352 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1766
C:\WINDOWS\System32\Normaliz.dll:Normaliz.dll (75AA0000), size: 28672 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\System32\WINTRUST.dll:WINTRUST.dll (75AB0000), size: 311296 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\WINDOWS\SYSTEM32\MSVCP140.dll:MSVCP140.dll (74E20000), size: 446464 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 14.29.30037.0
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll:VCRUNTIME140.dll (74350000), size: 81920 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 14.29.30037.0
C:\WINDOWS\SYSTEM32\Secur32.dll:Secur32.dll (6DB50000), size: 40960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\SSPICLI.DLL:SSPICLI.DLL (70870000), size: 135168 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1586
C:\WINDOWS\SYSTEM32\MSASN1.dll:MSASN1.dll (73830000), size: 57344 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\System32\NSI.dll:NSI.dll (76720000), size: 28672 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.610
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL:dhcpcsvc6.DLL (6F3B0000), size: 81920 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL:dhcpcsvc.DLL (6F390000), size: 90112 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\system32\mswsock.dll:mswsock.dll (707B0000), size: 335872 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\CRYPTSP.dll:CRYPTSP.dll (71390000), size: 77824 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\system32\rsaenh.dll:rsaenh.dll (71360000), size: 192512 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1052
C:\WINDOWS\SYSTEM32\CRYPTBASE.dll:CRYPTBASE.dll (71350000), size: 40960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\System32\imagehlp.dll:imagehlp.dll (75EB0000), size: 102400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1415
C:\WINDOWS\SYSTEM32\gpapi.dll:gpapi.dll (71330000), size: 122880 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.572
C:\Program Files (x86)\Epic Games\Launcher\Portal\Extras\Overlay\EOSOVH-Win32-Shipping.dll:EOSOVH-Win32-Shipping.dll (507E0000), size: 552960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 1.2.5.1200
C:\WINDOWS\SYSTEM32\d3d11.dll:d3d11.dll (6A280000), size: 1966080 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1741
C:\WINDOWS\SYSTEM32\dxgi.dll:dxgi.dll (61DF0000), size: 798720 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\WINDOWS\System32\MSCTF.dll:MSCTF.dll (75DD0000), size: 868352 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1806
C:\WINDOWS\SYSTEM32\cryptnet.dll:cryptnet.dll (708A0000), size: 155648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\WINDOWS\system32\nvspcap.dll:nvspcap.dll (0E8A0000), size: 2191360 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 3.20.5.70
C:\WINDOWS\SYSTEM32\ntmarta.dll:ntmarta.dll (75010000), size: 167936 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\dxcore.dll:dxcore.dll (6C740000), size: 180224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\system32\napinsp.dll:napinsp.dll (6E340000), size: 69632 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\system32\pnrpnsp.dll:pnrpnsp.dll (6E320000), size: 90112 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\system32\wshbth.dll:wshbth.dll (6E1C0000), size: 65536 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\system32\NLAapi.dll:NLAapi.dll (6E180000), size: 90112 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\DNSAPI.dll:DNSAPI.dll (70600000), size: 593920 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1620
C:\WINDOWS\System32\winrnr.dll:winrnr.dll (6E1B0000), size: 57344 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\System32\DriverStore\FileRepository\nvrzi.inf_amd64_837808f7a3306943\nvldumd.dll:nvldumd.dll (6A460000), size: 884736 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 27.21.14.6109
C:\WINDOWS\System32\DriverStore\FileRepository\nvrzi.inf_amd64_837808f7a3306943\nvwgf2um.dll:nvwgf2um.dll (14BC0000), size: 38359040 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 27.21.14.6109
C:\WINDOWS\System32\clbcatq.dll:clbcatq.dll (76030000), size: 516096 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2001.12.10941.16384
C:\WINDOWS\system32\wbem\wbemprox.dll:wbemprox.dll (6B630000), size: 53248 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1320
C:\WINDOWS\SYSTEM32\wbemcomn.dll:wbemcomn.dll (6B5C0000), size: 458752 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1566
C:\WINDOWS\system32\wbem\wbemsvc.dll:wbemsvc.dll (6E170000), size: 65536 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1320
C:\WINDOWS\system32\wbem\fastprox.dll:fastprox.dll (6E0A0000), size: 823296 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\amsi.dll:amsi.dll (6DBD0000), size: 102400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1620
C:\WINDOWS\SYSTEM32\USERENV.dll:USERENV.dll (734D0000), size: 151552 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.572
C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2205.7-0\X86\MpOav.dll:MpOav.dll (6DB60000), size: 442368 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 4.18.2205.7
C:\WINDOWS\System32\MMDevApi.dll:MMDevApi.dll (50770000), size: 438272 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1503
C:\WINDOWS\System32\DEVOBJ.dll:DEVOBJ.dll (73670000), size: 147456 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1620
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL:AUDIOSES.DLL (0E760000), size: 1269760 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1741
C:\WINDOWS\SYSTEM32\powrprof.dll:powrprof.dll (74FC0000), size: 278528 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\UMPDC.dll:UMPDC.dll (73820000), size: 53248 (result: 0), SymType: '-deferred-', PDB: ''
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll:resourcepolicyclient.dll (50760000), size: 61440 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\xinput1_3.dll:xinput1_3.dll (00400000), size: 90112 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 9.18.944.0
C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_5b87a6d6dce2309d\igd10iumd32.dll:igd10iumd32.dll (18DA0000), size: 5296128 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 30.0.101.1339
C:\WINDOWS\SYSTEM32\ncrypt.dll:ncrypt.dll (6ED60000), size: 135168 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\NTASN1.dll:NTASN1.dll (6ED90000), size: 163840 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_5b87a6d6dce2309d\igdgmm32.dll:igdgmm32.dll (6A540000), size: 3108864 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 30.0.101.1339
C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_5b87a6d6dce2309d\igc32.dll:igc32.dll (5ED60000), size: 47734784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 30.0.101.1339
C:\WINDOWS\SYSTEM32\dcomp.dll:dcomp.dll (1A290000), size: 1462272 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1741
C:\WINDOWS\SYSTEM32\textinputframework.dll:textinputframework.dll (6D6D0000), size: 757760 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1741
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll:CoreUIComponents.dll (6D3B0000), size: 2613248 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\WINDOWS\SYSTEM32\CoreMessaging.dll:CoreMessaging.dll (6D630000), size: 634880 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.867
C:\WINDOWS\SYSTEM32\wintypes.dll:wintypes.dll (6A090000), size: 897024 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1682
C:\WINDOWS\SYSTEM32\dbghelp.dll:dbghelp.dll (6B2D0000), size: 1605632 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.1052

========== OUTPUTTING STACK TRACE ==================

  ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 18770530)
  ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 18770530)
0x18770530 ((<unknown>)) (function-name not available)

========== END OF STACKTRACE ===========

A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/Users/xxxxxxxx/AppData/Local/Temp/DefaultCompany/Epic EOS Test/Crashes
```

**Comment by kamyker** [comment]
x64 also crashes for me

**Comment by pal-cathar** [comment]
I confirm the crash occur on our project,

Unity Version: Unity 2020.3.33f1
Plugin Version: 2.0.1

**Comment by domlaurenti** [comment]
Adding this to the August Update (which is scheduled for EOM August). 

I'll talk to the team and see what we can do with escalating this.

**Comment by JarrydHuntley** [comment]
@domlaurenti Thanks for logging this. Please let me know if there are any workaround, we're set to go live next week.

**Comment by pew-dahs** [comment]
There's a new 2.0.2 release with a small update that should fix the x86 crashing issue.

**Comment by pal-cathar** [comment]
The crash is still present on my side. Happen at launch after the splash screen when the lib is loaded. Both in 86x or 64x. I tried to set the x86 libs loading at launch but the crash is even earlier.

========== OUTPUTTING STACK TRACE ==================

0x5DF161A5 (GfxPluginNativeRender-x86) global_log_flush_with_function
0x5DF181C6 (GfxPluginNativeRender-x86) UnityPluginLoad
0x78C4BBE7 (UnityPlayer) UnityMain
0x78C4A09F (UnityPlayer) UnityMain
0x78C4B8B6 (UnityPlayer) UnityMain
0x78C51DD4 (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 78A6D16F)
0x78A6D16F (UnityPlayer) (function-name not available)
0x78A6E625 (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 006C1015)
0x006C1015 (Monorail Stories) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 006C11D9)
0x006C11D9 (Monorail Stories) (function-name not available)
0x76E6FA29 (KERNEL32) BaseThreadInitThunk
0x77257A9E (ntdll) RtlGetAppContainerNamedObjectPath
0x77257A6E (ntdll) RtlGetAppContainerNamedObjectPath

========== END OF STACKTRACE ===========

**Comment by domlaurenti** [comment]
Hello all, can you update to the latest 2.1.0 version and tell us if the issue is still occurring for you?

**Comment by pal-cathar** [comment]
I'm able to reproduce the issue 100%. However, the source of the issue is likely not what it's written previously. I wanted to test in an empty project and found the game booting fine, so I tried to enter any data EOSConfigEditor panel... That is when the issue begins to happen. 

I assume something in the setting, like a bad setting or an invalid config, makes the game crash on boot... without an indicator of the error nor pointing to any change required to make it work (specific invalid information in the config).

Note that I removed the Linux libs from the zip to have a full Unity project under 25mb attach here, but the project demo is 100% crash and the issue is linked to the EOSConfigEditor 
[EGS_Test.zip](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/9470162/EGS_Test.zip)

**Comment by domlaurenti** [comment]
Thanks for the response. I'm gonna get this escalated to the team.

**Comment by scovertb** [comment]
This appears fixed in 2.1.2. Reopen this issue if the problem persists. There's a bug in the EOS config editor that will cause an error when no config file exists, but this can be resolved for now by entering anything in the encryption key field.
