### ISSUE TITLE
Epic command line arguments are being parsed wrong

### ISSUE THREAD

**Issue by pjuke** [PlayEveryWare/eos_plugin_for_unity#274]
**Describe the bug**
Recently Epic Launcher changed their way of formatting the command line arguments being sent to the application.
This results in that no sandbox or deployment id's are being overriden; the plugin will always use the default one provided in the configuration file.

The old format looked something like this:
`game.exe -epicusername USER -epicsandboxid ID`

While the new way is `=` separated like this:
`game.exe -epicusername=USER -epicsandboxid=ID`

Also the sandboxid is not always a 32 char HEX-string. It can contain various characters like dash (`-`) and other special characters. We got it working by disabling this check as well.

**To Reproduce**
Try to start your game in a different sandbox environment, and it will always fall back to the development (or the default one given in the configuration file that is).

**Expected behavior**
To parse the command line arguments correctly, as shown above.

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Standalone build
 - 2.2.1/2.2.0

**Additional context**
We have successfully modified the native GFX plugin and the code to adjust to this change and can confirm that it works as expected in the dev, stage and live environments. I'm not really comfortable doing a PR though, but may consider it if it's easer for you to make this change. This thread is mainly for other users to know that it currently does not work as expected :) 

Thank you anyway for this plugin, it is really well-written and has saved us a lot of work getting our game onto the Epic Store!

**Comment by FColor04** [comment]
I saw it being fixed in few weeks old commit but I can't compile it from source without further getting null returned from GetPlatformInterface or something like that, with additional error description being "probably error happened in Gfx" etc

**Comment by SourceByteDev** [comment]
The problem still persists.

**Comment by andrew-hirata-playeveryware** [comment]
This should be resolved by the 'April' release, which will be happening soon.

**Comment by Xenyrt** [comment]
Hello to the dev team!

The problem still seems to persist, although I haven't determined the precise cause.
The overrided values are completely ignored and the default SandBoxId/DeploymentId are always used.

In fact, I have the following behavior:
If I configure the default SandboxId/DeploymentId with Dev values, configure an override with Stage values and then play the Stage version from EGS, the overlay will show the unlocked state of the Dev version's achievements.
On the other hand, if I configure the default SandboxID/DeploymentId with Stage values, configure an override with Dev values and then play the Dev version from EGS, the overlay will show the unlocked state of the Stage version's achievements.

Do you have a solution to this issue, which is causing my project submission to fail?

Thanks in advance.

**Comment by andrew-hirata-playeveryware** [comment]
@Xenyrt what version of the Plugin and Unity are you using? I might have to follow up with someone on my side to determine if what you said should work, but it's my understanding that it should be handled with the current version of the plugin.

@FColor04; those build issues are probably due to not having the native code in the plugin, did you follow the steps in the [contributor notes](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/readme.md#build-steps-for-native-libraries) about building the libraries? 

@SourceByteDev, which version of the EOS Plugin are you using?

**Comment by Xenyrt** [comment]
Hello Andrew and thank you for your reply.

I use the plugin in version 2.3.0 (latest release tarball of
eos_plugin_for_unity_upm) and Unity 2022.2.17f1. I installed/uninstalled
the plugin several times, restarted Unity between each installation... with
the same result.

For information, I had the SandboxId/DevelopmentId override problem on
version 2.2.0. I waited for your correction on version 2.3.0 to redo my
tests.
My SandboxId Dev and Stage have the character "-" and are of the form
p-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX (I know that a user had noted a problem
of string comparison with special characters).

Don't hesitate to ask me if you need any further information.

Thank you in advance.

Guillaume Vidal
Draw Me A Pixel <https://www.drawmeapixel.com/>
